/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    Success,
    SuccessFromJSON,
    SuccessToJSON,
} from '../models'

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
    /**
     */
    async authRaw(): Promise<runtime.ApiResponse<Success>> {
        const queryParameters: runtime.HTTPQuery = {}

        const headerParameters: runtime.HTTPHeaders = {}

        const response = await this.request({
            path: `/api/auth`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        })

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessFromJSON(jsonValue))
    }

    /**
     */
    async auth(): Promise<Success> {
        const response = await this.authRaw()
        return await response.value()
    }
}
