"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiErrorToJSON = exports.ApiErrorFromJSONTyped = exports.ApiErrorFromJSON = void 0;
function ApiErrorFromJSON(json) {
    return ApiErrorFromJSONTyped(json, false);
}
exports.ApiErrorFromJSON = ApiErrorFromJSON;
function ApiErrorFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        error: json['error'],
    };
}
exports.ApiErrorFromJSONTyped = ApiErrorFromJSONTyped;
function ApiErrorToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        error: value.error,
    };
}
exports.ApiErrorToJSON = ApiErrorToJSON;
