"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderFeatureToJSON = exports.ProviderFeatureFromJSONTyped = exports.ProviderFeatureFromJSON = exports.ProviderFeature = void 0;
/**
 *
 * @export
 * @enum {string}
 */
var ProviderFeature;
(function (ProviderFeature) {
    ProviderFeature["Search"] = "search";
})(ProviderFeature = exports.ProviderFeature || (exports.ProviderFeature = {}));
function ProviderFeatureFromJSON(json) {
    return ProviderFeatureFromJSONTyped(json, false);
}
exports.ProviderFeatureFromJSON = ProviderFeatureFromJSON;
function ProviderFeatureFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
exports.ProviderFeatureFromJSONTyped = ProviderFeatureFromJSONTyped;
function ProviderFeatureToJSON(value) {
    return value;
}
exports.ProviderFeatureToJSON = ProviderFeatureToJSON;
