"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderToJSON = exports.ProviderFromJSONTyped = exports.ProviderFromJSON = void 0;
const _1 = require("./");
function ProviderFromJSON(json) {
    return ProviderFromJSONTyped(json, false);
}
exports.ProviderFromJSON = ProviderFromJSON;
function ProviderFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
        categories: json['categories'].map(_1.ProviderCategoryFromJSON),
        features: json['features'].map(_1.ProviderFeatureFromJSON),
    };
}
exports.ProviderFromJSONTyped = ProviderFromJSONTyped;
function ProviderToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        categories: value.categories.map(_1.ProviderCategoryToJSON),
        features: value.features.map(_1.ProviderFeatureToJSON),
    };
}
exports.ProviderToJSON = ProviderToJSON;
