"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderCategoryToJSON = exports.ProviderCategoryFromJSONTyped = exports.ProviderCategoryFromJSON = void 0;
const _1 = require("./");
function ProviderCategoryFromJSON(json) {
    return ProviderCategoryFromJSONTyped(json, false);
}
exports.ProviderCategoryFromJSON = ProviderCategoryFromJSON;
function ProviderCategoryFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
        id: json['id'],
        subcategories: json['subcategories'].map(_1.ProviderCategorySubcategoriesFromJSON),
    };
}
exports.ProviderCategoryFromJSONTyped = ProviderCategoryFromJSONTyped;
function ProviderCategoryToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        id: value.id,
        subcategories: value.subcategories.map(_1.ProviderCategorySubcategoriesToJSON),
    };
}
exports.ProviderCategoryToJSON = ProviderCategoryToJSON;
