"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderTorrentToJSON = exports.ProviderTorrentFromJSONTyped = exports.ProviderTorrentFromJSON = void 0;
const helpers_1 = require("../helpers");
const _1 = require("./");
function ProviderTorrentFromJSON(json) {
    return ProviderTorrentFromJSONTyped(json, false);
}
exports.ProviderTorrentFromJSON = ProviderTorrentFromJSON;
function ProviderTorrentFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
        magnet: json['magnet'],
        seeds: json['seeds'],
        downloads: !helpers_1.exists(json, 'downloads') ? undefined : json['downloads'],
        peers: json['peers'],
        size: json['size'],
        time: !helpers_1.exists(json, 'time') ? undefined : json['time'],
        link: json['link'],
        isVip: !helpers_1.exists(json, 'isVip') ? undefined : json['isVip'],
        imdb: !helpers_1.exists(json, 'imdb') ? undefined : json['imdb'],
        numFiles: !helpers_1.exists(json, 'numFiles') ? undefined : json['numFiles'],
        category: _1.ProviderCategorySubcategoriesFromJSON(json['category']),
    };
}
exports.ProviderTorrentFromJSONTyped = ProviderTorrentFromJSONTyped;
function ProviderTorrentToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        magnet: value.magnet,
        seeds: value.seeds,
        downloads: value.downloads,
        peers: value.peers,
        size: value.size,
        time: value.time,
        link: value.link,
        isVip: value.isVip,
        imdb: value.imdb,
        numFiles: value.numFiles,
        category: _1.ProviderCategorySubcategoriesToJSON(value.category),
    };
}
exports.ProviderTorrentToJSON = ProviderTorrentToJSON;
