"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProviderCategorySubcategoriesToJSON = exports.ProviderCategorySubcategoriesFromJSONTyped = exports.ProviderCategorySubcategoriesFromJSON = void 0;
function ProviderCategorySubcategoriesFromJSON(json) {
    return ProviderCategorySubcategoriesFromJSONTyped(json, false);
}
exports.ProviderCategorySubcategoriesFromJSON = ProviderCategorySubcategoriesFromJSON;
function ProviderCategorySubcategoriesFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
        id: json['id'],
    };
}
exports.ProviderCategorySubcategoriesFromJSONTyped = ProviderCategorySubcategoriesFromJSONTyped;
function ProviderCategorySubcategoriesToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        id: value.id,
    };
}
exports.ProviderCategorySubcategoriesToJSON = ProviderCategorySubcategoriesToJSON;
