"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SuccessToJSON = exports.SuccessFromJSONTyped = exports.SuccessFromJSON = void 0;
function SuccessFromJSON(json) {
    return SuccessFromJSONTyped(json, false);
}
exports.SuccessFromJSON = SuccessFromJSON;
function SuccessFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        success: json['success'],
    };
}
exports.SuccessFromJSONTyped = SuccessFromJSONTyped;
function SuccessToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        success: value.success,
    };
}
exports.SuccessToJSON = SuccessToJSON;
