"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TorrentToJSON = exports.TorrentFromJSONTyped = exports.TorrentFromJSON = void 0;
const _1 = require("./");
function TorrentFromJSON(json) {
    return TorrentFromJSONTyped(json, false);
}
exports.TorrentFromJSON = TorrentFromJSON;
function TorrentFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        link: json['link'],
        infoHash: json['infoHash'],
        name: json['name'],
        started: json['started'],
        updated: json['updated'],
        files: json['files'].map(_1.TorrentFileFromJSON),
        downloaded: json['downloaded'],
        downloadSpeed: json['downloadSpeed'],
    };
}
exports.TorrentFromJSONTyped = TorrentFromJSONTyped;
function TorrentToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        link: value.link,
        infoHash: value.infoHash,
        name: value.name,
        started: value.started,
        updated: value.updated,
        files: value.files.map(_1.TorrentFileToJSON),
        downloaded: value.downloaded,
        downloadSpeed: value.downloadSpeed,
    };
}
exports.TorrentToJSON = TorrentToJSON;
