"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TorrentFileToJSON = exports.TorrentFileFromJSONTyped = exports.TorrentFileFromJSON = void 0;
function TorrentFileFromJSON(json) {
    return TorrentFileFromJSONTyped(json, false);
}
exports.TorrentFileFromJSON = TorrentFileFromJSON;
function TorrentFileFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json['name'],
        path: json['path'],
        type: json['type'],
        length: json['length'],
        stream: json['stream'],
    };
}
exports.TorrentFileFromJSONTyped = TorrentFileFromJSONTyped;
function TorrentFileToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        path: value.path,
        type: value.type,
        length: value.length,
        stream: value.stream,
    };
}
exports.TorrentFileToJSON = TorrentFileToJSON;
