"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsageToJSON = exports.UsageFromJSONTyped = exports.UsageFromJSON = void 0;
function UsageFromJSON(json) {
    return UsageFromJSONTyped(json, false);
}
exports.UsageFromJSON = UsageFromJSON;
function UsageFromJSONTyped(json, ignoreDiscriminator) {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        totalDiskSpace: json['totalDiskSpace'],
        freeDiskSpace: json['freeDiskSpace'],
        usedTorrentSpace: json['usedTorrentSpace'],
    };
}
exports.UsageFromJSONTyped = UsageFromJSONTyped;
function UsageToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        totalDiskSpace: value.totalDiskSpace,
        freeDiskSpace: value.freeDiskSpace,
        usedTorrentSpace: value.usedTorrentSpace,
    };
}
exports.UsageToJSON = UsageToJSON;
