/* tslint:disable */
/* eslint-disable */
/**
 * Torrents Stream Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum ProviderFeatureModel {
    Search = 'search',
}

export function ProviderFeatureModelFromJSON(json: any): ProviderFeatureModel {
    return ProviderFeatureModelFromJSONTyped(json, false)
}

export function ProviderFeatureModelFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ProviderFeatureModel {
    return json as ProviderFeatureModel
}

export function ProviderFeatureModelToJSON(value?: ProviderFeatureModel | null): any {
    return value as any
}
