name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Sleep for 300 seconds
        run: sleep 300s
        shell: bash

      - uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
          keep_files: true
